name: Upgrade cluster-monitoring-operator jsonnet dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' #@weekly
jobs:
  jsonnet-update:
    uses: rhobs/syncbot/.github/workflows/cmo-make-targets.yaml@main
    with:
      go-version: 1.17
      make-targets: update generate
      pr-title: "[bot] Automated jsonnet dependencies update"
      pr-body: |
        ## Description
        This is an automated jsonnet dependencies update performed from CI.

        If you wish to perform this manually, execute the following commands from cluster-monitoring-operator repo,
        ```
        make update
        make generate
        ```
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
